from django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('home', views.home, name = 'home'),
    path('login', views.login, name = 'login'),
    path('notification', views.notification, name = 'notification'),
    path('openorder', views.openorder, name='openorder'),
    path('SalesEachMonth', views.sales, name='sales'),
    path('SalesCustomer',views.salesCompany, name = 'salesCompany'),
    path('TopTwo', views.weather_chart_view, name='weather_chart_view'),
    path('WABASH', views.weatherByCity, name='weatherByCity'),
    path('PurchaseDep', views.purchaseCode, name = 'purchaseCode'),
    path('PurchaseEachMonth', views.purchase, name = 'purchase'),
    path('InventoryEachMonth', views.inventory, name = 'inventory'),
    path('MonthlyRevenue', views.revenue, name = 'revenue'),
    
    path('OrderRep', views.orderRep, name = 'orderrep'),
    path('OrderCustomer', views.orderCustomer, name = 'ordercustomer'),
    path('OrderDate', views.orderDate, name = 'orderdate'),
    path('OrderBl', views.orderBl, name = 'orderbl'),
    path('OrderCl', views.orderCl, name = 'ordercl'),
    path('OrderDa', views.orderDa, name = 'orderda'),
    path('OrderS1', views.orderS1, name = 'orders1'),
    path('OrderS2', views.orderS2, name = 'orders2'),
    path('OrderS3', views.orderS3, name = 'orders3'),
    path('OrderS4', views.orderS4, name = 'orders4'),
    
    path('PivotBudget', views.pivotBudget, name = 'pivotbudget'),
    path('BudgetReport', views.budgetReport, name = 'budgetreport'),

    path('OveralloneDep', views.overalloneDep, name = 'overallonedep'),
    path('OveralltwoDep', views.overalltwoDep, name = 'overalltwodep'),
    path('OverallthreeDep', views.overallthreeDep, name = 'overallthreedep'),

    path('FoundrymainCompare', views.foundrymainCompare, name = 'foundrymaincompare'),
    path('FoundrymainMini', views.foundrymainMini, name = 'foundrymainmini'),
    path('FoundrymainAll',views.foundrymainAll, name = 'foundrymainall'),
    
    path('FoundryoneMonth', views.foundryoneMonth, name = 'foundryonemonth'),
    path('FoundrytwoMonth', views.foundrytwoMonth, name = 'foundrytwomonth'),    
    path('FoundrythreeMonth', views.foundrythreeMonth, name = 'foundrythreemonth'),
    path('FoundryallMonth', views.foundryallMonth, name = 'foundryallmonth'),
    path('FoundrycompareMonth', views.foundrycompareMonth, name = 'foundrycomparemonth'),
    
    path('FoundryoneVendor', views.foundryoneVendor, name = 'foundryonevendor'),
    path('FoundrytwoVendor', views.foundrytwoVendor, name = 'foundrytwovendor'),
    path('FoundrythreeVendor', views.foundrythreeVendor, name = 'foundrythreevendor'),
    path('FoundryallVendor', views.foundryallVendor, name = 'foundryallvendor'),
    
    path('FoundryoneItem', views.foundryoneItem, name = 'foundryoneitem'),
    path('FoundrytwoItem', views.foundrytwoItem, name = 'foundrytwoitem'),
    path('FoundrythreeItem', views.foundrythreeItem, name = 'foundrythreeitem'),
    path('FoundryallItem', views.foundryallItem, name = 'foundryallitem'),

    path('FoundryoneExpense', views.foundryoneExpense, name = 'foundryoneexpense'),
    path('FoundrytwoExpense', views.foundrytwoExpense, name = 'foundrytwoexpense'),
    path('FoundrythreeExpense', views.foundrythreeExpense, name = 'foundrythreeexpense'),
    
    path('FoundryonetopItem', views.foundryonetopItem, name = 'foundryonetopitem'),
    path('FoundrytwotopItem', views.foundrytwotopItem, name = 'foundrytwotopitem'),
    path('FoundrythreetopItem', views.foundrythreetopItem, name = 'foundrythreetopitem'),

    path('FoundrycompareScrap', views.foundrycompareScrap, name = 'foundrycomparescrap'),
    path('FoundrycomparePrime', views.foundrycomparePrime, name = 'foundrycompareprime'),
    path('FoundrycompareLog', views.foundrycompareLog, name = 'foundrycomparelog'),

    path('ExtrusiononeItem', views.extrusiononeItem, name = 'extrusiononeitem'),
    path('ExtrusiontwoItem', views.extrusiontwoItem, name = 'extrusiontwoitem'),
    path('ExtrusionthreeItem', views.extrusionthreeItem, name = 'extrusionthreeitem'),

    path('ExtrusiononetopItem', views.extrusiononetopItem, name = 'extrusiononetopitem'),
    path('ExtrusiontwotopItem', views.extrusiontwotopItem, name = 'extrusiontwotopitem'),
    path('ExtrusionthreetopItem', views.extrusionthreetopItem, name = 'extrusionthreetopitem'),

    path('ExtrusiononeMonth', views.extrusiononeMonth, name = 'extrusiononemonth'),
    path('ExtrusiontwoMonth', views.extrusiontwoMonth, name = 'extrusiontwomonth'),
    path('ExtrusionthreeMonth', views.extrusionthreeMonth, name = 'extrusionthreemonth'),
    path('ExtrusionallMonth', views.extrusionallMonth, name = 'extrusionallmonth'),
    path('ExtrusioncompareMonth', views.extrusioncompareMonth, name = 'extrusioncomparemonth'),

    path('ExtrusioncompareMain', views.extrusioncompareMain, name = 'extrusioncomparemain'),
    
    path('SalesoneRep', views.salesoneRep, name = 'salesonerep'),
    path('SalestwoRep', views.salestwoRep, name = 'salestworep'),
    path('SalesthreeRep', views.salesthreeRep, name = 'salesthreerep'),
    path('SalesoneCustomer', views.salesoneCustomer, name = 'salesonecustomer'),
    path('SalestwoCustomer', views.salestwoCustomer, name = 'salestwocustomer'),
    path('SalesthreeCustomer', views.salesthreeCustomer, name = 'salesthreecustomer'),
    path('SalesoneMonth', views.salesoneMonth, name = 'salesonemonth'),
    path('SalestwoMonth', views.salestwoMonth, name = 'salestwomonth'),
    path('SalesthreeMonth', views.salesthreeMonth, name = 'salesthreemonth'),
    path('SalesallMonth', views.salesallMonth, name = 'salesallmonth'),

    path('SalesoneBl', views.salesoneBl, name = 'salesonebl'),
    path('SalestwoBl', views.salestwoBl, name = 'salestwobl'),
    path('SalesthreeBl', views.salesthreeBl, name = 'salesthreebl'),
    path('SalesallBl', views.salesallBl, name = 'salesallbl'),
    path('SalescompareBl', views.salescompareBl, name = 'salescomparebl'),
    path('SalesoneCl', views.salesoneCl, name = 'salesonecl'),
    path('SalestwoCl', views.salestwoCl, name = 'salestwocl'),
    path('SalesthreeCl', views.salesthreeCl, name = 'salesthreecl'),
    path('SalesallCl', views.salesallCl, name = 'salesallcl'),
    path('SalescompareCl', views.salescompareCl, name = 'salescomparecl'),
    path('SalesoneDa', views.salesoneDa, name = 'salesoneda'),
    path('SalestwoDa', views.salestwoDa, name = 'salestwoda'),
    path('SalesthreeDa', views.salesthreeDa, name = 'salesthreeda'),
    path('SalesallDa', views.salesallDa, name = 'salesallda'),
    path('SalescompareDa', views.salescompareDa, name = 'salescompareda'),
    path('SalesoneS1', views.salesoneS1, name = 'salesones1'),
    path('SalestwoS1', views.salestwoS1, name = 'salestwos1'),
    path('SalesthreeS1', views.salesthreeS1, name = 'salesthrees1'),
    path('SalesallS1', views.salesallS1, name = 'salesallsl'),
    path('SalescompareS1', views.salescompareS1, name = 'salescompares1'),
    path('SalesoneS2', views.salesoneS2, name = 'salesones2'),
    path('SalestwoS2', views.salestwoS2, name = 'salestwos2'),
    path('SalesthreeS2', views.salesthreeS2, name = 'salesthrees2'),
    path('SalesallS2', views.salesallS2, name = 'salesalls2'),
    path('SalescompareS2', views.salescompareS2, name = 'salescompares2'),
    path('SalesoneS3', views.salesoneS3, name = 'salesones3'),
    path('SalestwoS3', views.salestwoS3, name = 'salestwos3'),
    path('SalesthreeS3', views.salesthreeS3, name = 'salesthrees3'),
    path('SalesallS3', views.salesallS3, name = 'salesalls3'),
    path('SalescompareS3', views.salescompareS3, name = 'salescompares3'),
    path('SalesoneS4', views.salesoneS4, name = 'salesones4'),
    path('SalestwoS4', views.salestwoS4, name = 'salestwos4'),
    path('SalesthreeS4', views.salesthreeS4, name = 'salesthrees4'),
    path('SalesallS4', views.salesallS4, name = 'salesalls4'),
    path('SalescompareS4', views.salescompareS4, name = 'salescompares4'),

    path('SalesoneDep', views.salesoneDep, name = 'salesonedep'),
    path('SalestwoDep', views.salestwoDep, name = 'salestwodep'),
    path('SalesthreeDep', views.salesthreeDep, name = 'salesthreedep'),
    path('SalesallDep', views.salesallDep, name = 'salesalldep'),

    path('SalesextrusionDep', views.salesextrusionDep, name = 'salesextrusiondep'),
    path('SalesfabricationDep', views.salesfabricationDep, name = 'salesfabricationdep'),
    path('SalesanodizingDep', views.salesanodizingDep, name = 'salesanodizingdep'),
    
]
